//@create-index
export { titleLens } from './titleLens'
export { descriptionLens } from './descriptionLens'
export { idLens } from './idLens'
export { imagesLens } from './imagesLens'
export { instructorLens } from './instructorLens'
export { maxInscriptionsLens } from './maxInscriptionsLens'
export { orderLens } from './orderLens'
export { slugLens } from './slugLens'
export { instructorIdLens } from './instructorIdLens'

export { Path as titlePath } from './titleLens'
export { Path as descriptionPath } from './descriptionLens'
export { Path as imagesPath } from './imagesLens'
export { Path as instructorPath } from './instructorLens'
export { Path as maxInscriptionsPath } from './maxInscriptionsLens'
export { Path as orderPath } from './orderLens'
export { Path as slugPath } from './slugLens'
export { Path as instructorIdPath } from './instructorIdLens'
